using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Windows.Forms.VisualStyles;

namespace DefendTheCity
{
    public partial class Form1 : Form
    {
        // create class member variables that can be used anywhere in the class.
        // created timer, initial game duration time, countdown timer, points gained per second of play and groupbox label
        int m_timer = 0;
        int timerleft = 30;
        int m_countdowntimer = 0;
        string m_selectedcitydata = "selected city";
        string m_comboboxselection = "";
        int m_cityattackvalue = 0;
        int m_cityhealthvalue = 0;
        int m_citydefensespots = 0;
        int m_pointspersecond = 0;
        decimal pointcounter = 0;

        public Form1()
        {
            InitializeComponent();
            //initializes form with hidden sequence arrows for user to follow
            SequenceArrow1.Visible = false;
            SequenceArrow2.Visible = false;
            SequenceArrow3.Visible = false;
        }

        private void label1_Click(object sender, EventArgs e)
        {

        }

        private void startbutton_Click(object sender, EventArgs e)
        {
            // when the user clicks on the start button, the game first checks to see if a city is selected.
            // If a city is not locked in, a message will display saying "Need to lock in a city first"
            if (selectedcitydata.Text == "selected city")
            {
                MessageBox.Show("Need to lock in a city first");
            }
            // If a city is locked in, a message box displays informing the user to Defend the City.
            else
            {
               
                // Checks if you selected a duration to the game
                if (gamedurationcombobox.Text == "0")
                {
                    MessageBox.Show("Need to select a game length");
                }
                else {
                    MessageBox.Show("Defend the City!");
                    // After the user acknowledges the messagebox, the timer loads and begins countdown.
                    timerleft = int.Parse(gamedurationcombobox.SelectedItem.ToString());
                    //timer displays number with seconds
                    countdowntimer.Text = timerleft.ToString() + " " + "seconds";
                    //timer starts
                    timer.Start();
                }
            }
        }

        private void timer_Tick(object sender, EventArgs e)
        {
            //timer counts down from selected time as the duration of the game length.
            if (timerleft > 0)
            {
                //timer subtracts 1 second
                timerleft--;
                //timer displays every second during countdown
                countdowntimer.Text = timerleft.ToString() + " " + "seconds";
                //the points generated by each city are added to the available points.
                pointcounter += decimal.Parse(pointspersecond.Text.ToString());
                //available points are displayed on the screen
                availablepoints.Text = pointcounter.ToString();
            }
            else
            {
                // Once the timer finishes counting down, it stops and a message shows up saying times up!
                timer.Stop();
                countdowntimer.Text = "times up!";
               
            }

        }

        private void citylockbutton_Click(object sender, EventArgs e)
        {
            // checks if city is selected from combobox
            if (selectcitycombobox.Text == "")
            {
                // if a city is not selected, does not let you continue with starting game
                MessageBox.Show("Need to select a city first");
            }
            else
            {
                // shows sequence arrow for flow of game
                SequenceArrow2.Visible = true;
            // after the user selects their city, the citylock button places the city name and data into the group box fields
            selectedcitydata.Text = selectcitycombobox.SelectedItem.ToString();
            cityremaininghealth.Text = cityhealthvalue.Text;
            }
        }

        private void selectedcitydata_Enter(object sender, EventArgs e)
        {

        }

        private void Form1_Load(object sender, EventArgs e)
        {
            //add the following 6 cities to the city selection combobox
            selectcitycombobox.Items.Add("Tokyo");
            selectcitycombobox.Items.Add("San Francisco");
            selectcitycombobox.Items.Add("New York");
            selectcitycombobox.Items.Add("London");
            selectcitycombobox.Items.Add("Moscow");
            selectcitycombobox.Items.Add("Rome");
            this.Controls.Add(selectcitycombobox);

            

            //adds the following duration times to the duration selection combobox
            gamedurationcombobox.Items.Add("30");
            gamedurationcombobox.Items.Add("60");
            gamedurationcombobox.Items.Add("90");
            gamedurationcombobox.Items.Add("120");
            this.Controls.Add(gamedurationcombobox);
        }

        private void selectcitycombobox_SelectedIndexChanged(object sender, EventArgs e)
        {
            //If loops for each change of city selection to alter the baseline stats of attack, health, defense spots, and points gained per second
            if (selectcitycombobox.SelectedItem.ToString() == "Tokyo")
            {
                cityattackvalue.Text = "100";
                cityhealthvalue.Text = "100";
                citydefensespots.Text = "2";
                pointspersecond.Text = "1";
            }
            if (selectcitycombobox.SelectedItem.ToString() == "San Francisco")
            {
            cityattackvalue.Text = "150";
            cityhealthvalue.Text = "50";
            citydefensespots.Text = "2";
            pointspersecond.Text = "1.5";
            }
            if(selectcitycombobox.SelectedItem.ToString() == "New York")
            {
                cityattackvalue.Text = "50";
                cityhealthvalue.Text = "150";
                citydefensespots.Text = "1";
                pointspersecond.Text = "1";
            }
            if (selectcitycombobox.SelectedItem.ToString() == "London")
            {
                cityattackvalue.Text = "75";
                cityhealthvalue.Text = "100";
                citydefensespots.Text = "2";
                pointspersecond.Text = "1.5";
            }
            if (selectcitycombobox.SelectedItem.ToString() == "Moscow")
            {
                cityattackvalue.Text = "175";
                cityhealthvalue.Text = "50";
                citydefensespots.Text = "3";
                pointspersecond.Text = "1";
            }
            if (selectcitycombobox.SelectedItem.ToString() == "Rome")
            {
                cityattackvalue.Text = "50";
                cityhealthvalue.Text = "150";
                citydefensespots.Text = "2";
                pointspersecond.Text = "2";
            }
            // displays sequence arrow when a city is picked in the combobox
            SequenceArrow1.Visible = true;
        }

        private void gamedurationcombobox_SelectedIndexChanged(object sender, EventArgs e)
        {
            // checks if the game duration is not equal to 0 and if thats true, displays sequence arrow.
            if (gamedurationcombobox.Text != "0")
            {
                SequenceArrow3.Visible = true;
            }
        }
    }
}
